#include "charizard.h"
#include <iostream>
#include "fireball.h"

using namespace std;

//constructor
Charizard::Charizard(QPixmap *pm, int nx, int ny) : Thing(pm, nx, ny)
{
	invincible = false;
}

//deconstructor
Charizard::~Charizard()
{
}

//move function
void Charizard::move()
{
 //movement generated by player (spacebar)
}

bool Charizard::collidesWithItem(Thing* t)
{
	QRectF playerRect(x,y,80,60);
	//const QRectF playerRect = boundingRect();
	QRectF thingRect (t->boundingRect());
	thingRect.moveTo(t->getX(),t->getY());
	if ((playerRect.intersects(thingRect)))
	{	
		return true;
	}
	else {return false;}
}
