#include "charizard.h"
#include <iostream>
#include "fireball.h"

using namespace std;

//constructor
Charizard::Charizard(QPixmap *pm, int nx, int ny) : Thing(pm, nx, ny)
{
	invincible = false;
}

//deconstructor
Charizard::~Charizard()
{
}

//move function
void Charizard::move()
{
 //movement generated by player (spacebar)
}

bool Charizard::collidesWithItem(Thing* t)
{
	QRectF playerRect(x+5,y+5,75,55);
	QRectF thingRect (t->getX(),t->getY(),t->getWidth(),t->getHeight());
	//cthingRect.setRect();
	if ((playerRect.intersects(thingRect)))
	{	
		return true;
	}
	else {return false;}
}
